### PR TITLE
add markdown files processing

### LINKED ISSUE #6: add markdown files processing
add the process to parse italic and bold  for Markdown file.

### PR DESCRIPTION
**Pull request by WangGithub0**
- change version to 0.0.2
- add parsing markdown in README
- process markdown
- parsing italic and bold

 Closes https://github.com/kliu57/go-go-web/issues/6

### CODE REVIEW

**Comment by WangGithub0** [comment]
@kliu57  I have added the new feature, help me review please.

**Comment by kliu57** [comment]
image
I found a bug in the italics functionalities. See above screenshot.
Also, please make sure you add or edit a test file (.md) so that the test file tests both italics and bold and some edge cases (* characters with nothing in between)

**Comment by WangGithub0** [comment]
> image I found a bug in the italics functionalities. See above screenshot. Also, please make sure you add or edit a test file (.md) so that the test file tests both italics and bold and some edge cases (* characters with nothing in between)

have fixed it and add the examples
image

**Comment by kliu57** [comment]
looks good

**Pull request merged**
